Spp tactical integration
ONSdigital/rm-reporting pull request #45
Opened 2021-01-13 19:29 UTC by akssinhaamit

# Motivation and Context

# What has changed

# How to test?

# Links

2021-01-18 16:06 UTC, insacuri reviewed
I didn't do a full review sorry, but there are few things I saw.

2021-01-18 16:32 UTC, warrenbailey requested changes

2021-01-18 16:32 UTC, warrenbailey commented on _infra/docker/Dockerfile
> +CMD ["gunicorn", "-b", "0.0.0.0:8080", "rm_reporting:app"]
Doesn't this remove the workers?

2021-01-18 16:40 UTC, akssinhaamit commented on _infra/helm/reporting/values.yaml
> +  bucket: ras-rm-notify-test
I will provide the dev as the default value although it gets governed by config

2021-01-18 16:40 UTC, akssinhaamit commented on rm_reporting/resources/response_chasing.py
> +            collex_details = engine.execute(text(collex_status)).first()
👍

2021-01-18 16:40 UTC, akssinhaamit commented on _infra/docker/Dockerfile
> +CMD ["gunicorn", "-b", "0.0.0.0:8080", "rm_reporting:app"]
👍

2021-01-18 16:42 UTC, akssinhaamit commented on _infra/helm/reporting/templates/deployment.yaml
> +          {{- if .Values.aws.enabled }}
Sure.. in both the cases we (RAS/RM) won't be owning AWS account and I believe dev cluster will not like to communicate to AWS services. Hence keeping AWS enabled seems ok to me :-)

2021-01-18 16:44 UTC, akssinhaamit commented on _infra/helm/reporting/templates/deployment.yaml
> +                name: aws-credentials
sure, but we can change it anytime we introduce another account in future.

2021-01-19 08:48 UTC, warrenbailey commented
/deploy baileyw

2021-01-19 11:05 UTC, warrenbailey requested changes

2021-01-19 19:25 UTC, akssinhaamit commented on rm_reporting/resources/spp_reporting.py
> +        'SELECT c.survey_uuid AS surveyId, c.id as collectionExerciseId '
👍

2021-01-19 19:27 UTC, akssinhaamit commented on rm_reporting/resources/spp_reporting.py
> +    respondent_query = "SELECT r.id, " \
Having respondent with the same query will duplicate the data on case level and then we will need to have additional logic to sort it out hence it was kept as a seperate step

2021-01-19 19:40 UTC, akssinhaamit commented on rm_reporting/resources/spp_reporting.py
> +        day = datetime.today().strftime('%d%m%Y')
👍

2021-01-19 20:19 UTC, akssinhaamit commented on rm_reporting/resources/spp_reporting.py
> +        raise NoDataException
👍

2021-01-20 07:56 UTC, warrenbailey commented on rm_reporting/resources/spp_reporting.py
> +    respondent_query = "SELECT r.id, " \
as discussed happy with this now 👍

2021-01-20 08:02 UTC, warrenbailey approved these changes

2021-01-20 08:03 UTC, warrenbailey commented
LGTM just need to sort the lint error 👍

2021-01-20 12:10 UTC, merged